services:
  - type: web
    name: psychaid-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_USER
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false 